//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CSHOTEL_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CSHOTEL_HPP


class CSHotel {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CSHOTEL_HPP