//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CAHOTEL_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CAHOTEL_HPP


class CAHotel {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CAHOTEL_HPP