//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CSRESERVA_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CSRESERVA_HPP


class CSReserva {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CSRESERVA_HPP