//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CARESERVA_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CARESERVA_HPP


class CAReserva {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CARESERVA_HPP