//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CAQUARTO_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CAQUARTO_HPP


class CAQuarto {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CAQUARTO_HPP