//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CSQUARTO_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CSQUARTO_HPP


class CSQuarto {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CSQUARTO_HPP