//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CSHOSPEDAGEM_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CSHOSPEDAGEM_HPP


class CSHospedagem {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CSHOSPEDAGEM_HPP