//
// Created by caleb on 14/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_CAHOSPEDAGEM_HPP
#define GERENCIADOR_DE_HOTEIS_UNB_CAHOSPEDAGEM_HPP


class CAHospedagem {
};


#endif //GERENCIADOR_DE_HOTEIS_UNB_CAHOSPEDAGEM_HPP