//
// Created by caleb on 26/10/2025.
//

#ifndef ANTIGO_PROJETO_HOTEL_CLION_MAIN_IML_TESTSMODULARES_H
#define ANTIGO_PROJETO_HOTEL_CLION_MAIN_IML_TESTSMODULARES_H

void executarTestsModulares();

#endif //ANTIGO_PROJETO_HOTEL_CLION_MAIN_IML_TESTSMODULARES_H