@startuml
skinparam linetype ortho
skinparam packageStyle rectangle
package "Hotelaria" #LightGreen {
class SistemaHacker {
		- ControladorInterfaceGerente controladorGerente
	}
}
package "Hotelaria" #LightGreen {
class BancoDeDados {
		+ bool abrindoConexao();
		+ bool fechandoConexao();
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceGerente {
		- PersistenciaGerente persistencia
		- bool executando = true
		- bool estaAutenticado = false
		+ ControladorInterfaceGerente()
		+ InterfaceServicoAutenticavel *controladora_servico_autenticavel
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceHospede {
		- PersistenciaHospede persistencia
		- bool executando = true
		+ ControladorInterfaceHospede()
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceHotel {
		- PersistenciaHotel persistencia
		- bool executando = true
		+ ControladorInterfaceHotel()
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceQuarto {
		+ ControladorInterfaceQuarto()
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceReserva {
		+ ControladorInterfaceReserva()
	}
}
package "Hotelaria" #LightGreen {
class EnumConversor {
		+ static int StatusSolicitacaoHospedagemParaInteiro(StatusSolicitacaoHospedagem status)
		+ static StatusSolicitacaoHospedagem InteiroParaStatusSolicitacaoHospedagem(int valor)
	}
}
package "Hotelaria" #LightGreen {
enum StatusSolicitacaoHospedagem {
PENDENTE
APROVADO
RECUSADO
	}
}
package "Hotelaria" #LightGreen {
class FabricaGerenciavel {
		+ shared_ptr<T> criar()
		+ shared_ptr<T> objeto
		+ shared_ptr<T> objeto
		+ shared_ptr<T> objeto
		+ shared_ptr<T> objeto
		+ void executarMenu(string tituloStr, bool &executando)
		+ Menu menu
		+ const int OPCAO_VOLTAR_AO_SISTEMA
		+ const int OPCAO_CRIAR
		+ const int OPCAO_LER
		+ const int OPCAO_ATUALIZAR
		+ const int OPCAO_REMOVER
		+ int opcao
		+ Println("Voce Saiu do Menu CRUD!");
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoCRUD {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoExibirMenu {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceFabricaGerenciavel {
		+ virtual unique_ptr<InterfaceApresentacaoCRUD> criar()
	}
}
package "Hotelaria" #LightGreen {
class Capacidade {
		- int capacidadeInt
		- void validar(int valor); // Metodo de validacao
		+ Capacidade()
		+ explicit Capacidade(const int &valor)
		+ void setValor(const int &valor)
		+ int getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Cartao {
		- string cartaoStr
		- void validar(string valor);
		+ Cartao()
		+ explicit Cartao(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Codigo {
		- string codigoStr
		- void validar(string valor); // Metodo de validacao
		+ Codigo()
		+ explicit Codigo(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Data {
		+ int dia
		+ int mes
		+ int ano
		+ static int const JAN = 1
		+ static int const FEV = 2
		+ static int const MAR = 3
		+ static int const ABR = 4
		+ static int const MAI = 5
		+ static int const JUN = 6
		+ static int const JUL = 7
		+ static int const AGO = 8
		+ static int const SET = 9
		+ static int const OUT = 10
		+ static int const NOV = 11
		+ static int const DEZ = 12
		+ Data()
		+ explicit Data(const string &dataStr);
		+ string toString()
		+ void setData(int d, int m, int a);
		+ int getDia();
		+ int getMes();
		+ int getAno();
	}
}
package "Hotelaria" #LightGreen {
class Dinheiro {
		- int valor
		- void validar(int dinheiroInt); // Metodo de validacao
		+ Dinheiro()
		+ explicit Dinheiro(const int &dinheiroInt)
		+ void setValor(int dinheiroInt)
		+ int getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Email {
		- string emailStr
		- void validar(const string &valor);
		+ Email()
		+ explicit Email(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Endereco {
		- string enderecoStr
		- void validar(string valor); // Metodo de validacao
		+ Endereco()
		+ explicit Endereco(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Nome {
		- string nomeStr
		- void validar(const string &valor); // Metodo de validacao
		+ Nome()
		+ explicit Nome(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Numero {
		- string numeroStr
		- void validar(string valor); // Metodo de validacao
		+ Numero()
		+ explicit Numero(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Ramal {
		- string ramalStr
		- void validar(const string &valor); // Metodo de validacao
		+ Ramal()
		+ explicit Ramal(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Senha {
		- string senhaStr
		- void validar(string valor); // Metodo de validacao
		+ Senha()
		+ explicit Senha(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Telefone {
		- string telefoneStr
		- void validar(string valor);
		+ Telefone()
		+ explicit Telefone(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Gerente {
		- Ramal ramal
		- Senha senha
		+ Gerente()
		+ Pessoa(Nome(), Email())
		+ Gerente(Nome nomePessoaObj, Email emailPessoaObj, Ramal ramal, Senha senha)
		+ Pessoa(nomePessoaObj, emailPessoaObj),
		+ Gerente(GerenteDTO &gerente_dto)
		+ Pessoa(Nome(gerente_dto.getNome()), Email(gerente_dto.getEmail()))
		+ void setNome(const Nome &newNome)
		+ void setEmail(const Email &newEmail)
		+ void setRamal(const Ramal &newRamal)
		+ void setSenha(const Senha &newSenha)
		+ string getRamal() const;
		+ string getSenha() const;
	}
}
package "Hotelaria" #LightGreen {
class Hospede {
		- Endereco endereco
		- Cartao cartao
		+ Hospede()
		+ Pessoa(Nome(), Email())
		+ Hospede(Nome nomePessoaObj, Email emailPessoaObj, Endereco endereco, Cartao cartao)
		+ void setNome(const Nome &newNome)
		+ void setEmail(const Email &newEmail)
		+ void setEndereco(const Endereco &newEndereco)
		+ void setCartao(const Cartao &newCartao)
		+ string getEndereco() const
		+ string getCartao() const
	}
}
package "Hotelaria" #LightGreen {
class Hotel {
		- Nome nome
		- Endereco endereco
		- Telefone telefone
		- Codigo codigo
		+ Hotel()
		+ Hotel(Nome nome, Endereco endereco, Telefone telefone, Codigo codigo)
		+ Hotel(HotelDTO &hotel_dto)
		+ void setNome(const Nome &newNome)
		+ void setEndereco(const Endereco &newEndereco)
		+ void setTelefone(const Telefone &newTelefone)
		+ void setCodigo(const Codigo &newCodigo)
		+ string getNome() const
		+ string getEndereco() const
		+ string getTelefone() const
		+ string getCodigo() const
	}
}
package "Hotelaria" #LightGreen {
class Pessoa {
		- Nome nome
		- Email email
		+ Pessoa(Nome nomeObj, Email emailObj)
		+ void setPessoaNome(const Nome &valor)
		+ void setPessoaEmail(const Email &valor)
		+ string getNome() const;
		+ string getEmail() const;
	}
}
package "Hotelaria" #LightGreen {
class Quarto {
		- Numero numero
		- Capacidade capacidade
		- Dinheiro diaria
		- Ramal ramal
		+ Quarto()
		+ Quarto(Numero numero, Capacidade capacidade, Dinheiro diaria, Ramal ramal)
		+ void setNumero(const Numero &newNumero)
		+ void setCapacidade(const Capacidade &newCapacidade)
		+ void setDiaria(const Dinheiro &newDiaria)
		+ void setRamal(const Ramal &newRamal)
		+ string getNumero() const
		+ int getCapacidade() const
		+ int getDiaria() const
		+ string getRamal() const
	}
}
package "Hotelaria" #LightGreen {
class Reserva {
		- Data chegada
		- Data partida
		- Dinheiro dinheiro
		- Codigo codigo
		+ Reserva()
		+ Reserva(Data chegada, Data partida, Dinheiro dinheiro, Codigo codigo)
		+ void setChegada(const Data &newChegada)
		+ void setPartida(const Data &newPartida)
		+ void setDinheiro(const Dinheiro &newDinheiro)
		+ void setCodigo(const Codigo &newCodigo)
		+ Data getChegada() const
		+ Data getPartida() const
		+ int getDinheiro() const
		+ string getCodigo() const
	}
}
package "Hotelaria" #LightGreen {
class SolicitacaoHospedagem {
		- string hospedeId
		- string hotelId
		- string quartoId
		- Data chegada
		- Data partida
		- StatusSolicitacaoHospedagem status
		- string motivoRecusa
		+ SolicitacaoHospedagem()
		+ void setHospedeId(const string &id)
		+ void setHotelId(const string &id)
		+ void setQuartoId(const string &id)
		+ void setChegada(const Data &d)
		+ void setPartida(const Data &d)
		+ void setStatus(StatusSolicitacaoHospedagem s)
		+ void setMotivoRecusa(const string &motivo)
		+ string getHospedeId() const
		+ string getHotelId() const
		+ string getQuartoId() const
		+ Data getChegada() const
		+ Data getPartida() const
		+ StatusSolicitacaoHospedagem getStatus() const
		+ string getMotivoRecusa() const
	}
}
package "Hotelaria" #LightGreen {
class GerenteDTO {
		- int id
		- string nome
		- string email
		- string ramal
		+ GerenteDTO()
		+ GerenteDTO(int id, string nome, string email, string ramal)
		+ int getId() const
		+ void setId(int id)
		+ string getNome() const
		+ void setNome(const string &nome)
		+ string getEmail() const
		+ void setEmail(const string &email)
		+ string getRamal() const
		+ void setRamal(const string &ramal)
	}
}
package "Hotelaria" #LightGreen {
class HotelDTO {
		- int id
		- string nome
		- string endereco
		- string telefone
		- string codigo
		+ HotelDTO()
		+ HotelDTO(int id, string nome, string endereco, string telefone, string codigo)
		+ int getId() const
		+ void setId(int id)
		+ string getNome() const
		+ void setNome(const string &nome)
		+ string getEndereco() const
		+ void setEndereco(const string &endereco)
		+ string getTelefone() const
		+ void setTelefone(const string &telefone)
		+ string getCodigo() const
		+ void setCodigo(const string &codigo)
	}
}
package "Hotelaria" #LightGreen {
class PersistenciaGerente {
		+ bool inserir(Gerente &gerente);
		+ vector<GerenteDTO *> listar();
		+ bool atualizar(int id, const Gerente &gerente);
		+ bool excluirPorId(int id);
		+ bool autenticarGerente(const string &email, const string &senha);
		+ optional<GerenteDTO> buscaGerentePorID(int id);
	}
}
package "Hotelaria" #LightGreen {
class PersistenciaHospede {
		- string caminho = "Dados_Hospedes.txt"
		+ vector<Hospede *> listar();
		+ bool criar(Hospede &gerente);
	}
}
package "Hotelaria" #LightGreen {
class PersistenciaHotel {
		+ bool inserir(Hotel *hotel);
		+ vector<HotelDTO *> listar();
		+ optional<HotelDTO> buscaHotelPorID(int id);
		+ bool atualizar(int id, const Hotel &hotel);
	}
}
package "Hotelaria" #LightGreen {
class PersistenciaSolicitacaoHospedagem {
		+ static void salvar(const SolicitacaoHospedagem &s);
		+ static vector<SolicitacaoHospedagem> buscarPorEmail(const string &email);
		+ static vector<SolicitacaoHospedagem> buscarPorStatus(int status);
		+ static void atualizar(const SolicitacaoHospedagem &s);
	}
}
package "Hotelaria" #LightGreen {
class Sistema {
		- bool executando = true
		- ControladoraApresentacaoAcessoGerente contoladoraApresentacaoAcessoGerente
		- ControladoraApresentacaoAcessoHospede contoladoraApresentacaoAcessoHospede
		- bool getExecutandoSistema();
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoAutenticavel {
		- bool estaAutenticado = false
		+ bool autenticar(Email*) override;
		+ void setEstaAutenticado(bool estaAutenticado) override;
		+ bool getEstaAutenticado() override;
		+ InterfaceServicoAutenticavel* getHacke();
		+ setControladoraServicoAutenticavel(InterfaceServicoAutenticavel *controladora_servico_autenticavel)
		+ setEstaAutenticado(bool estaAutenticado)
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoAutenticavel {
		+ bool autenticar(const Email, const Senha) override;
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoAutenticavel {
		+ virtual bool autenticar(Email*)
		+ virtual void setEstaAutenticado(bool estaAutenticado)
		+ virtual bool getEstaAutenticado()
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoAutenticavel {
		+ virtual bool autenticar(const Email, const Senha)
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoHospede {
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoHospede {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoHospede {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoHospede {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoHotel {
		+ string valor
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoHotel {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoHotel {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoHotel {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoPessoal {
		- const static int INCLUIR = 1
		- const static int REMOVER = 2
		- const static int PESQUISAR = 3
		- const static int EDITAR = 4
		- const static int RETORNAR = 5
		+ void executar(const Email);
		+ void setControladoraServicoPessoal(InterfaceServicoPessoal *);
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoPessoal {
		+ bool incluir(const Gerente);
		+ bool remover(const Email email);
		+ bool pesquisar(Gerente);
		+ bool editar(const Gerente);
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoPessoal {
		- virtual void executar(const Email email)
		- virtual void setControladoraServicoPessoal(InterfaceServicoPessoal *)
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoPessoal {
		+ virtual bool incluir(const Gerente)
		+ virtual bool remover(const Email email)
		+ virtual bool pesquisar(Gerente)
		+ virtual bool editar(const Gerente)
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoQuarto {
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoQuarto {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoQuarto {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoQuarto {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoReserva {
		+ ControladorInterfaceReserva();
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoReserva {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoReserva {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoReserva {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoAcessoGerente {
		- ControladorInterfaceGerente controladorGerente
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoAcessoHospede {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoAcesso {
	}
}
package "Utils" #DarkRed {
class Utils {
		- bool verificaSeENumero(const string &str);
	}
}
package "Hotelaria" #LightGreen {
class Versao {
		+ static string getData()
		+ static string getVersaoCompleta()
	}
}
package "IO" #Orange {
class IO {
		- string LerLinha();
		- string LerOpcao();
		- bool tentarNovamente();
		- void Println(const string &mensagem);
		- void Print(const string &mensagem);
	}
}
package "VisualizadorDeMenu" #Gray {
class Menu {
		- vector<MenuItem> menuItens
		- int contador = -1
		+ int adcionarItens(string nome);
		+ vector<MenuItem> listar();
		+ int executa(string tituloStr);
	}
}
package "VisualizadorDeMenu" #Gray {
class MenuItem {
		- string nome
		- string valor
		- int valorConstante
		+ MenuItem(string nomeStr, string valorStr, int valorConstanteInt)
		+ string getNome();
		+ string getValor();
		+ int getValorConstante();
	}
}
package "VisualizadorDeTabela" #Gold {
class Atributo {
		- string nome
		- string valor
		+ Atributo()
		+ Atributo(string nome, string valor)
		+ void setNome(string nome);
		+ void setValor(string valor);
		+ string getNome();
		+ string getValor();
	}
}
package "VisualizadorDeTabela" #Gold {
class Linha {
		- vector<shared_ptr<Atributo> > atributos
		+ Linha()
		+ void atributo(string nome, string valor);
		+ void atributo(string nome, int valor);
		+ vector<shared_ptr<Atributo> > getAtributos()
	}
}
package "VisualizadorDeTabela" #Gold {
class Tabela {
		- vector<shared_ptr<Linha> > linhas
		+ Tabela()
		+ Linha *criarObj();
		+ void exibirTabela(string titulo);
	}
}
package "VisualizadorDeTabela" #Gold {
class TamanhoAtributo {
		- string nome
		- int tamanho = 0
		+ TamanhoAtributo()
		+ TamanhoAtributo(string nome, int tamanho)
		+ void setNome(string nome);
		+ void setTamanho(int tamanho);
		+ string getNome();
		+ int getTamanho();
	}
}
package "Teste" #Purple {
interface InterfaceDeTeste {
		- static int contTodalTestes
		- static int contTodalTestesOk
		- static int contTodalTestesProblema
		- static vector<string> listaFalhas
		+ static const int DEVE_DAR_ERRADO = -1
		+ static const int DEVE_DAR_CERTO = 1
		+ static void checaResultado(int esperando_resultado, int resultado_teste);
		+ static void apresentacaoTeste(const string &valor);
		+ static void apresentacaoTeste(const int &valor);
		+ static void registrarFalha(const string &dominio, const string &entrada, const string &erro);
		+ static int getTestes();
		+ static int getTestesOk();
		+ static int getTestesProblema();
	}
}
package "Teste" #Purple {
class SmokeTeste {
		+ Recebe o valor_teste como string (Implementação no .cpp)
		+ void testarDominio(int esperando_resultado,const string &valor_teste,const string &dominio,function<void()> funcao_validacao
		+ Recebe o valor_teste como Template T (para int, float, etc.)
		+ void testarDominio(int esperando_resultado,const T &valor_teste,const string &dominio,function<void()> funcao_validacao);
		+ Recebe o valor_teste como string (Implementação no .cpp)
		+ void testarEntidade(int esperando_resultado,const string &valor_teste,const string &entidade,function<void()> funcao_validacao);
		+ Recebe o valor_teste como Template T (para int, float, etc.)
		+ void testarEntidade(int esperando_resultado,const T &valor_teste,const string &entidade,function<void()> funcao_validacao);
		+ testarDominio(int esperando_resultado,const T &valor_teste,const string &dominio,function<void()> funcao_validacao)
		+ string(valor_teste), // Conversão para string
		+ testarEntidade(int esperando_resultado,const T &valor_teste,const string &entidade,function<void()> funcao_validacao)
		+ string(valor_teste), // Conversão para string
	}
}
ControladorInterfaceGerente  --|> ControladoraApresentacaoAutenticavel : Herança
ControladorInterfaceGerente  ..|> InterfaceApresentacaoExibirMenu : Implementação
ControladorInterfaceGerente  ..|> InterfaceApresentacaoCRUD : Implementação
ControladorInterfaceHospede  ..|> InterfaceApresentacaoCRUD : Implementação
ControladorInterfaceHotel  ..|> InterfaceApresentacaoExibirMenu : Implementação
ControladorInterfaceHotel  ..|> InterfaceApresentacaoCRUD : Implementação
ControladorInterfaceQuarto  ..|> InterfaceApresentacaoExibirMenu : Implementação
ControladorInterfaceReserva  ..|> InterfaceApresentacaoExibirMenu : Implementação
Data  --|> exception : Herança
Gerente  --|> Pessoa : Herança
Hospede  --|> Pessoa : Herança
ControladoraApresentacaoAutenticavel  ..|> InterfaceApresentacaoAutenticavel : Implementação
ControladoraServicoAutenticavel  ..|> InterfaceServicoAutenticavel : Implementação
ControladoraApresentacaoHospede  ..|> InterfaceApresentacaoHospede : Implementação
ControladoraServicoHospede  ..|> InterfaceServicoHospede : Implementação
ControladoraServicoHotel  ..|> InterfaceServicoHotel : Implementação
ControladoraApresentacaoPessoal  ..|> InterfaceApresentacaoPessoal : Implementação
ControladoraServicoPessoal  ..|> InterfaceServicoPessoal : Implementação
ControladoraApresentacaoQuarto  ..|> InterfaceApresentacaoQuarto : Implementação
ControladoraServicoQuarto  ..|> InterfaceServicoQuarto : Implementação
ControladoraApresentacaoReserva  ..|> InterfaceApresentacaoReserva : Implementação
ControladoraServicoReserva  ..|> InterfaceServicoReserva : Implementação
ControladoraApresentacaoAcessoGerente  ..|> InterfaceApresentacaoAcesso : Implementação
ControladoraApresentacaoAcessoHospede  ..|> InterfaceApresentacaoAcesso : Implementação
SistemaHacker  --* ControladorInterfaceGerente : Composição
SistemaHacker  --* Gerente : Composição
BancoDeDados  --* Gerente : Composição
BancoDeDados  --* Hospede : Composição
BancoDeDados  --* Hotel : Composição
BancoDeDados  --* Quarto : Composição
BancoDeDados  --* Reserva : Composição
ControladorInterfaceGerente  --* Gerente : Composição
ControladorInterfaceGerente  --* PersistenciaGerente : Composição
ControladorInterfaceGerente  --* ControladoraServicoAutenticavel : Composição
ControladorInterfaceGerente  --* InterfaceServicoAutenticavel : Composição
ControladorInterfaceGerente  --* Menu : Composição
ControladorInterfaceHospede  --* Hospede : Composição
ControladorInterfaceHospede  --* PersistenciaHospede : Composição
ControladorInterfaceHospede  --* Menu : Composição
ControladorInterfaceHotel  --* Hotel : Composição
ControladorInterfaceHotel  --* PersistenciaHotel : Composição
ControladorInterfaceHotel  --* Menu : Composição
ControladorInterfaceQuarto  --* Quarto : Composição
ControladorInterfaceQuarto  --* Menu : Composição
ControladorInterfaceReserva  --* Reserva : Composição
ControladorInterfaceReserva  --* Menu : Composição
EnumConversor  --* StatusSolicitacaoHospedagem : Composição
EnumConversor  --* SolicitacaoHospedagem : Composição
FabricaGerenciavel  --* Menu : Composição
InterfaceApresentacaoExibirMenu  --* Menu : Composição
InterfaceFabricaGerenciavel  --* FabricaGerenciavel : Composição
InterfaceFabricaGerenciavel  --* InterfaceApresentacaoCRUD : Composição
Gerente  --* Email : Composição
Gerente  --* Nome : Composição
Gerente  --* Ramal : Composição
Gerente  --* Senha : Composição
Gerente  --* GerenteDTO : Composição
Hospede  --* Cartao : Composição
Hospede  --* Email : Composição
Hospede  --* Endereco : Composição
Hospede  --* Nome : Composição
Hotel  --* Codigo : Composição
Hotel  --* Endereco : Composição
Hotel  --* Nome : Composição
Hotel  --* Telefone : Composição
Hotel  --* HotelDTO : Composição
Pessoa  --* Email : Composição
Pessoa  --* Nome : Composição
Quarto  --* Capacidade : Composição
Quarto  --* Dinheiro : Composição
Quarto  --* Numero : Composição
Quarto  --* Ramal : Composição
Reserva  --* Codigo : Composição
Reserva  --* Data : Composição
Reserva  --* Dinheiro : Composição
SolicitacaoHospedagem  --* StatusSolicitacaoHospedagem : Composição
SolicitacaoHospedagem  --* Data : Composição
SolicitacaoHospedagem  --* Hospede : Composição
SolicitacaoHospedagem  --* Hotel : Composição
SolicitacaoHospedagem  --* Quarto : Composição
GerenteDTO  --* Email : Composição
GerenteDTO  --* Nome : Composição
GerenteDTO  --* Ramal : Composição
GerenteDTO  --* Gerente : Composição
HotelDTO  --* Codigo : Composição
HotelDTO  --* Endereco : Composição
HotelDTO  --* Nome : Composição
HotelDTO  --* Telefone : Composição
HotelDTO  --* Hotel : Composição
PersistenciaGerente  --* Gerente : Composição
PersistenciaGerente  --* GerenteDTO : Composição
PersistenciaHospede  --* Hospede : Composição
PersistenciaHotel  --* Hotel : Composição
PersistenciaHotel  --* HotelDTO : Composição
PersistenciaSolicitacaoHospedagem  --* Email : Composição
PersistenciaSolicitacaoHospedagem  --* SolicitacaoHospedagem : Composição
Sistema  --* Gerente : Composição
Sistema  --* Hospede : Composição
Sistema  --* ControladoraApresentacaoAcessoGerente : Composição
Sistema  --* ControladoraApresentacaoAcessoHospede : Composição
Sistema  --* Menu : Composição
ControladoraApresentacaoAutenticavel  --* Email : Composição
ControladoraApresentacaoAutenticavel  --* ControladoraServicoAutenticavel : Composição
ControladoraApresentacaoAutenticavel  --* InterfaceServicoAutenticavel : Composição
ControladoraServicoAutenticavel  --* Email : Composição
ControladoraServicoAutenticavel  --* Senha : Composição
InterfaceApresentacaoAutenticavel  --* Email : Composição
InterfaceApresentacaoAutenticavel  --* ControladoraServicoAutenticavel : Composição
InterfaceApresentacaoAutenticavel  --* InterfaceServicoAutenticavel : Composição
InterfaceServicoAutenticavel  --* Email : Composição
InterfaceServicoAutenticavel  --* Senha : Composição
ControladoraApresentacaoPessoal  --* Email : Composição
ControladoraApresentacaoPessoal  --* Pessoa : Composição
ControladoraApresentacaoPessoal  --* ControladoraServicoPessoal : Composição
ControladoraApresentacaoPessoal  --* InterfaceServicoPessoal : Composição
ControladoraServicoPessoal  --* Email : Composição
ControladoraServicoPessoal  --* Gerente : Composição
InterfaceApresentacaoPessoal  --* Email : Composição
InterfaceApresentacaoPessoal  --* Pessoa : Composição
InterfaceApresentacaoPessoal  --* ControladoraServicoPessoal : Composição
InterfaceApresentacaoPessoal  --* InterfaceServicoPessoal : Composição
InterfaceServicoPessoal  --* Email : Composição
InterfaceServicoPessoal  --* Gerente : Composição
InterfaceServicoPessoal  --* Pessoa : Composição
ControladoraApresentacaoReserva  --* ControladorInterfaceReserva : Composição
ControladoraApresentacaoReserva  --* Reserva : Composição
ControladoraApresentacaoReserva  --* Menu : Composição
ControladoraApresentacaoAcessoGerente  --* ControladorInterfaceGerente : Composição
ControladoraApresentacaoAcessoGerente  --* Gerente : Composição
ControladoraApresentacaoAcessoGerente  --* Menu : Composição
ControladoraApresentacaoAcessoHospede  --* Menu : Composição
InterfaceApresentacaoAcesso  --* Menu : Composição
Utils  --* Numero : Composição
Versao  --* Data : Composição
IO  --* Linha : Composição
Menu  --* MenuItem : Composição
MenuItem  --* Nome : Composição
MenuItem  --* Menu : Composição
Atributo  --* Nome : Composição
Linha  --* Atributo : Composição
Tabela  --* Linha : Composição
TamanhoAtributo  --* Nome : Composição
TamanhoAtributo  --* Atributo : Composição
@enduml
