@startuml
title Diagrama de Classes - MAC, MAA, MAP, MSA e MSP
skinparam linetype ortho

' ===== Interfaces globais =====
interface InterfaceApresentacaoAutenticavel
interface InterfaceApresentacaoPessoal
interface InterfaceServicoAutenticavel
interface InterfaceServicoPessoal

package "MAC" {
    interface InterfaceApresentacaoAcesso
}

package "MAA" {
  class ControladoraApresentacaoAutenticavel {
    +autenticar(email: Email, senha: Senha): bool
  }
  class Email
  class Senha
}

package "MAP" {
  class ControladoraApresentacaoPessoal {
    +gerenciar(gerente: Gerente, email: Email, senha: Senha)
  }
  class Gerente
  class Email
  class Senha
}

package "MSA" {
  class ControladoraServicoAutenticavel
}

package "MSP" {
  class ControladoraServicoPessoal
}

' ===== Relações =====
InterfaceApresentacaoAcesso --|> InterfaceApresentacaoAutenticavel
InterfaceApresentacaoAcesso --|> InterfaceApresentacaoPessoal
InterfaceApresentacaoAutenticavel <|-- ControladoraApresentacaoAutenticavel

ControladoraApresentacaoAutenticavel ..> InterfaceServicoAutenticavel
InterfaceServicoAutenticavel <|-- ControladoraServicoAutenticavel

InterfaceApresentacaoPessoal <|-- ControladoraApresentacaoPessoal
ControladoraApresentacaoPessoal ..> InterfaceServicoPessoal
InterfaceServicoPessoal <|-- ControladoraServicoPessoal

@enduml