@startuml
skinparam linetype ortho
skinparam packageStyle rectangle

' Classe abstrata Movimentacao
interface Movimentacao {
    + ligar()
    + desligar()
}

' Classe base Veiculo que implementa Movimentacao
class Veiculo {
    - Motor motor
    - string marca
    - string modelo
    - Velocidade velocidade
    - int ano
    + ligar()
    + desligar()
    + info()
}

' Herança
class Carro {
    - int numeroDePortas
    + abrirPorta()
    + ligar()
}

class Moto {
    - bool temPartidaEletrica
    + empinar()
    + ligar()
}

' Composição
class Motor {
    - int cilindradas
    - string tipoCombustivel
    + funcionar()
}

class Oficina {
    - string nome
    - string endereco
    - List<Veiculo> veiculos
    + adicionarVeiculo(Veiculo v)
    + listarVeiculos()
}

' Enum Velocidade
package "Pacote de Utilitarios" #LightGreen {
enum Velocidade {
    + LENTO
    + RAPIDO
    + ULTRARRAPIDO
}
}

' Relações

Veiculo --* Motor : Composição
Oficina --* Veiculo : Composição

Veiculo ..|> Movimentacao : Implementação

Moto  --|> Veiculo : Herança
Carro  --|> Veiculo : Herança

Veiculo --o Velocidade : Composição

@enduml
