@startuml
skinparam linetype ortho
skinparam packageStyle rectangle
package "Hotelaria" #LightGreen {
class BancoDeDados {
		+ bool abrindoConexao();
		+ bool fechandoConexao();
	}
}
package "Hotelaria" #LightGreen {
class Capacidade {
		- int capacidadeInt
		- void validar(int valor); // Metodo de validacao
		+ Capacidade()
		+ explicit Capacidade(const int &valor)
		+ void setValor(const int &valor)
		+ int getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Cartao {
		- string cartaoStr
		- void validar(string valor);
		+ Cartao()
		+ explicit Cartao(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Codigo {
		- string codigoStr
		- void validar(string valor); // Metodo de validacao
		+ Codigo()
		+ explicit Codigo(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Data {
		+ int dia
		+ int mes
		+ int ano
		+ static int const JAN = 1
		+ static int const FEV = 2
		+ static int const MAR = 3
		+ static int const ABR = 4
		+ static int const MAI = 5
		+ static int const JUN = 6
		+ static int const JUL = 7
		+ static int const AGO = 8
		+ static int const SET = 9
		+ static int const OUT = 10
		+ static int const NOV = 11
		+ static int const DEZ = 12
		+ Data()
		+ explicit Data(const string &dataStr);
		+ string toString()
		+ void setData(int d, int m, int a);
		+ int getDia();
		+ int getMes();
		+ int getAno();
	}
}
package "Hotelaria" #LightGreen {
class Dinheiro {
		- int valor
		- void validar(int dinheiroInt); // Metodo de validacao
		+ Dinheiro()
		+ explicit Dinheiro(const int &dinheiroInt)
		+ void setValor(int dinheiroInt)
		+ int getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Email {
		- string emailStr
		- void validar(const string &valor);
		+ Email()
		+ explicit Email(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Endereco {
		- string enderecoStr
		- void validar(string valor); // Metodo de validacao
		+ Endereco()
		+ explicit Endereco(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Nome {
		- string nomeStr
		- void validar(const string &valor); // Metodo de validacao
		+ Nome()
		+ explicit Nome(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Numero {
		- string numeroStr
		- void validar(string valor); // Metodo de validacao
		+ Numero()
		+ explicit Numero(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Ramal {
		- string ramalStr
		- void validar(const string &valor); // Metodo de validacao
		+ Ramal()
		+ explicit Ramal(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Senha {
		- string senhaStr
		- void validar(string valor); // Metodo de validacao
		+ Senha()
		+ explicit Senha(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const;
	}
}
package "Hotelaria" #LightGreen {
class Telefone {
		- string telefoneStr
		- void validar(string valor);
		+ Telefone()
		+ explicit Telefone(const string &valor)
		+ void setValor(const string &valor)
		+ string getValor() const
	}
}
package "Hotelaria" #LightGreen {
class Gerente {
		- Ramal ramal
		- Senha senha
		+ Gerente()
		+ Pessoa(Nome(), Email())
		+ Gerente(Nome nomePessoaObj, Email emailPessoaObj, Ramal ramal, Senha senha)
		+ Gerente(GerenteDTO &gerente_dto)
		+ Pessoa(Nome(gerente_dto.getNome()), Email(gerente_dto.getEmail()))
		+ void setNome(const Nome &newNome)
		+ void setEmail(const Email &newEmail)
		+ void setRamal(const Ramal &newRamal)
		+ void setSenha(const Senha &newSenha)
		+ string getRamal() const;
		+ string getSenha() const;
	}
}
package "Hotelaria" #LightGreen {
class Hospede {
		- Endereco endereco
		- Cartao cartao
		+ Hospede()
		+ Pessoa(Nome(), Email())
		+ Hospede(Nome nomePessoaObj, Email emailPessoaObj, Endereco endereco, Cartao cartao)
		+ void setNome(const Nome &newNome)
		+ void setEmail(const Email &newEmail)
		+ void setEndereco(const Endereco &newEndereco)
		+ void setCartao(const Cartao &newCartao)
		+ string getEndereco() const
		+ string getCartao() const
	}
}
package "Hotelaria" #LightGreen {
class Hotel {
		- Nome nome
		- Endereco endereco
		- Telefone telefone
		- Codigo codigo
		+ Hotel()
		+ Hotel(Nome nome, Endereco endereco, Telefone telefone, Codigo codigo)
		+ Hotel(HotelDTO &hotel_dto)
		+ void setNome(const Nome &newNome)
		+ void setEndereco(const Endereco &newEndereco)
		+ void setTelefone(const Telefone &newTelefone)
		+ void setCodigo(const Codigo &newCodigo)
		+ string getNome() const
		+ string getEndereco() const
		+ string getTelefone() const
		+ string getCodigo() const
	}
}
package "Hotelaria" #LightGreen {
class Pessoa {
		- Nome nome
		- Email email
		+ Pessoa(Nome nomeObj, Email emailObj)
		+ void setPessoaNome(const Nome &valor)
		+ void setPessoaEmail(const Email &valor)
		+ string getNome() const;
		+ string getEmail() const;
	}
}
package "Hotelaria" #LightGreen {
class Quarto {
		- Numero numero
		- Capacidade capacidade
		- Dinheiro diaria
		- Ramal ramal
		+ Quarto()
		+ Quarto(Numero numero, Capacidade capacidade, Dinheiro diaria, Ramal ramal);
		+ void setNumero(const Numero &newNumero);
		+ void setCapacidade(const Capacidade &newCapacidade);
		+ void setDiaria(const Dinheiro &newDiaria);
		+ void setRamal(const Ramal &newRamal);
		+ string getNumero() const;
		+ int getCapacidade() const;
		+ int getDiaria() const;
		+ string getRamal() const;
	}
}
package "Hotelaria" #LightGreen {
class Reserva {
		- Data chegada
		- Data partida
		- Dinheiro dinheiro
		- Codigo codigo
		+ Reserva()
		+ Reserva(Data chegada, Data partida, Dinheiro dinheiro, Codigo codigo)
		+ void setChegada(const Data &newChegada)
		+ void setPartida(const Data &newPartida)
		+ void setDinheiro(const Dinheiro &newDinheiro)
		+ void setCodigo(const Codigo &newCodigo)
		+ Data getChegada() const
		+ Data getPartida() const
		+ int getDinheiro() const
		+ string getCodigo() const
	}
}
package "Hotelaria" #LightGreen {
class SolicitacaoHospedagem {
		- string hospedeId
		- string hotelId
		- string quartoId
		- Data chegada
		- Data partida
		- StatusSolicitacaoHospedagem status
		- string motivoRecusa
		+ SolicitacaoHospedagem()
		+ void setHospedeId(const string &id)
		+ void setHotelId(const string &id)
		+ void setQuartoId(const string &id)
		+ void setChegada(const Data &d)
		+ void setPartida(const Data &d)
		+ void setStatus(StatusSolicitacaoHospedagem s)
		+ void setMotivoRecusa(const string &motivo)
		+ string getHospedeId() const
		+ string getHotelId() const
		+ string getQuartoId() const
		+ Data getChegada() const
		+ Data getPartida() const
		+ StatusSolicitacaoHospedagem getStatus() const
		+ string getMotivoRecusa() const
	}
}
package "Hotelaria" #LightGreen {
class GerenteDTO {
		- int gerenteId
		- string nome
		- string email
		- string ramal
		+ GerenteDTO()
		+ GerenteDTO(int gerenteId, string nome, string email, string ramal)
		+ int getGerenteId() const
		+ void setGerenteId(int valor)
		+ string getNome() const
		+ void setNome(const string &valor)
		+ string getEmail() const
		+ void setEmail(const string &valor)
		+ string getRamal() const
		+ void setRamal(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class HospedeDTO {
		- int hospedeId
		- string nome
		- string email
		- string endereco
		- string cartao
		+ HospedeDTO()
		+ HospedeDTO(int hospedeId, string nome, string email, string endereco, string cartao)
		+ int getId() const
		+ void setId(int valor)
		+ string getNome() const
		+ void setNome(const string &valor)
		+ string getEmail() const
		+ void setEmail(const string &valor)
		+ string getEndereco() const
		+ void setEndereco(const string &valor)
		+ string getCartao() const
		+ void setCartao(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class HotelDTO {
		- int hotelId
		- string nome
		- string endereco
		- string telefone
		- string codigo
		+ HotelDTO()
		+ HotelDTO(int hotelId, string nome, string endereco, string telefone, string codigo)
		+ int getId() const
		+ void setId(int valor)
		+ string getNome() const
		+ void setNome(const string &valor)
		+ string getEndereco() const
		+ void setEndereco(const string &valor)
		+ string getTelefone() const
		+ void setTelefone(const string &valor)
		+ string getCodigo() const
		+ void setCodigo(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class PessoaDTO {
		- int pessoaId
		- string nome
		- string email
		+ PessoaDTO()
		+ PessoaDTO(int pessoaId, string nome, string email)
		+ int getPessoaId() const
		+ void setPessoaId(int valor)
		+ string getNome() const
		+ void setNome(const string &valor)
		+ string getEmail() const
		+ void setEmail(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class QuartoDTO {
		- int quartoId
		- string numero
		- string capacidade
		- string dinheiro
		- string ramal
		+ QuartoDTO()
		+ QuartoDTO(int quartoId, string nome, string email, string dinheiro, string ramal)
		+ int getQuartoId() const
		+ void setQuartoId(int valor)
		+ string getNumero() const
		+ void setNumero(const string &valor)
		+ string getCapacidade() const
		+ void setCapacidade(const string &valor)
		+ string getDinheiro() const
		+ void setDinheiro(const string &valor)
		+ string getRamal() const
		+ void setRamal(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class ReservaDTO {
		- int reservaId
		- string chegada
		- string partida
		- string dinheiro
		- string codigo
		+ ReservaDTO()
		+ ReservaDTO(int reservaId, string chegada, string partida, string dinheiro, string codigo)
		+ int getReservaId() const
		+ void setReservaId(int valor)
		+ string getChegada() const
		+ void setChegada(const string &valor)
		+ string getPartida() const
		+ void setPartida(const string &valor)
		+ string getDinheiro() const
		+ void setDinheiro(const string &valor)
		+ string getCodigo() const
		+ void setCodigo(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class SolicitacaoHospedagemDTO {
		- int solicitacaoHospedagemId
		- int hospedeId
		- int hotelId
		- int quartoId
		- string chegada
		- string partida
		- string status
		- string motivoRecusa
		+ SolicitacaoHospedagemDTO()
		+ SolicitacaoHospedagemDTO(int solicitacaoHospedagemId, int hospedeId, int hotelId, int quartoId, string chegada, string partida, string(status), string motivoRecusa)
		+ int getSolicitacaoHospedagemId() const
		+ void setSolicitacaoHospedagemId(int valor)
		+ int getHospedeId() const
		+ void setHospedeId(int valor)
		+ int getHotelId() const
		+ void setHotelId(int valor)
		+ int getQuartoId() const
		+ void setQuartoId(int valor)
		+ string getChegada() const
		+ void setChegada(const string &valor)
		+ string getPartida() const
		+ void setPartida(const string &valor)
		+ string getStatus() const
		+ void setStatus(const string &valor)
		+ string getMotivoRecusa() const
		+ void setMotivoRecusa(const string &valor)
	}
}
package "Hotelaria" #LightGreen {
class Sistema {
		- bool executando = true
		- ControladoraApresentacaoAcessoGerente contoladoraApresentacaoAcessoGerente
		- ControladoraApresentacaoAcessoHospede contoladoraApresentacaoAcessoHospede
		- bool getExecutandoSistema();
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoAcesso {
		+ virtual void setControladoraServicoAcesso(InterfaceServicoAcesso *)
	}
}
package "Hotelaria" #LightGreen {
class InterfaceServicoAcesso {
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoAcessoGerente {
		- InterfaceServicoAcesso *controladora_servico_acesso_gerente
		- ControladorInterfaceGerente controladorGerente
		+ void setControladoraServicoAcesso(InterfaceServicoAcesso *) override;
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoAcessoHospede {
		- InterfaceServicoAcesso *controladora_servico_acesso_hospede
		+ void setControladoraServicoAcesso(InterfaceServicoAcesso *) override;
	}
}
class ControladoraServicoAcessoGerente {
	}
class ControladoraServicoAcessoHospede {
	}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoAutenticavel {
		+ virtual bool autenticar(Email *)
		+ virtual void setControladoraServicoAutenticavel(InterfaceServicoAutenticavel *)
		+ virtual void setEstaAutenticado(bool estaAutenticado)
		+ virtual bool getEstaAutenticado()
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoAutenticavel {
		+ virtual bool autenticar(const Email, const Senha)
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoAutenticavel {
		- InterfaceServicoAutenticavel *controladora_servico_autenticavel
		- bool estaAutenticado = false
		+ bool autenticar(Email *) override;
		+ void setControladoraServicoAutenticavel(InterfaceServicoAutenticavel *) override;
		+ void setEstaAutenticado(bool estaAutenticado) override;
		+ bool getEstaAutenticado() override;
		+ InterfaceServicoAutenticavel *getHacke();
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoAutenticavel {
		+ bool autenticar(const Email, const Senha) override;
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceFabricaGerenciavel {
		+ virtual unique_ptr<MenuCRUD> criar()
	}
}
package "Hotelaria" #LightGreen {
class FabricaGerenciavel {
		+ shared_ptr<T> criar()
		+ shared_ptr<T> objeto
		+ shared_ptr<T> objeto
		+ shared_ptr<T> objeto
		+ shared_ptr<T> objeto
		+ void executarMenu(string tituloStr, bool &executando)
		+ Menu menu
		+ const int OPCAO_VOLTAR_AO_SISTEMA
		+ const int OPCAO_CRIAR
		+ const int OPCAO_LER
		+ const int OPCAO_ATUALIZAR
		+ const int OPCAO_REMOVER
		+ int opcao
		+ Println("Voce Saiu do Menu CRUD!");
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoGerente {
		- virtual void executar(const Email email)
		- virtual void setControladoraServicoPessoal(InterfaceServicoGerente *)
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoGerente {
		+ virtual bool incluir(const Gerente)
		+ virtual bool remover(const Email email)
		+ virtual bool pesquisar(Gerente)
		+ virtual bool editar(const Gerente)
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoGerente {
		- const static int INCLUIR = 1
		- const static int REMOVER = 2
		- const static int PESQUISAR = 3
		- const static int EDITAR = 4
		- const static int RETORNAR = 5
		+ void executar(const Email);
		+ void setControladoraServicoPessoal(InterfaceServicoGerente *) override;
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceGerente {
		- ControladoraPersistenciaGerente persistencia
		- bool executando = true
		- bool estaAutenticado = false
		+ ControladorInterfaceGerente();
	}
}
package "Hotelaria" #LightGreen {
class ControladoraPersistenciaGerente {
		+ bool inserir(Gerente &gerente);
		+ vector<GerenteDTO *> listar();
		+ bool atualizar(int id, const Gerente &gerente);
		+ bool excluirPorId(int id);
		+ bool autenticarGerente(const string &email, const string &senha);
		+ optional<GerenteDTO> buscaGerentePorID(int id);
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoGerente {
		+ bool incluir(const Gerente);
		+ bool remover(const Email email);
		+ bool pesquisar(Gerente);
		+ bool editar(const Gerente);
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoHospede {
		+ virtual bool valor()
		+ virtual void setControladoraServicoHospede(InterfaceServicoHospede *)
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoHospede {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoHospede {
		- InterfaceServicoHospede *controladora_servico_hospede
		+ bool valor() override;
		+ void setControladoraServicoHospede(InterfaceServicoHospede *) override;
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceHospede {
		- ControladoraPersistenciaHospede persistencia
		- bool executando = true
		+ ControladorInterfaceHospede()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraPersistenciaHospede {
		- string caminho = "Dados_Hospedes.txt"
		+ vector<Hospede *> listar();
		+ bool criar(Hospede &gerente);
	}
}
package "Hotelaria" #LightGreen {
class ControladoraPersistenciaSolicitacaoHospedagem {
		+ static void salvar(const SolicitacaoHospedagem &s);
		+ static vector<SolicitacaoHospedagem> buscarPorEmail(const string &email);
		+ static vector<SolicitacaoHospedagem> buscarPorStatus(int status);
		+ static void atualizar(const SolicitacaoHospedagem &s);
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoHospede {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoHotel {
		+ virtual bool valor()
		+ virtual void setControladoraServicoHotel(InterfaceServicoHotel *)
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoHotel {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoHotel {
		- InterfaceServicoHotel *controladora_servico_hotel
		+ bool valor() override;
		+ void setControladoraServicoHotel(InterfaceServicoHotel *) override;
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceHotel {
		- ControladoraPersistenciaHotel persistencia
		- bool executando = true
		+ ControladorInterfaceHotel()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraPersistenciaHotel {
		+ bool inserir(Hotel *hotel);
		+ vector<HotelDTO *> listar();
		+ optional<HotelDTO> buscaHotelPorID(int id);
		+ bool atualizar(int id, const Hotel &hotel);
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoHotel {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoQuarto {
		+ virtual bool valor()
		+ virtual void setControladoraServicoQuarto(InterfaceServicoQuarto *)
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoQuarto {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoQuarto {
		- InterfaceServicoQuarto *controladora_servico_quarto
		+ bool valor() override;
		+ void setControladoraServicoQuarto(InterfaceServicoQuarto *) override;
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceQuarto {
		+ ControladorInterfaceQuarto()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraPersistenciaQuarto {
		+ bool inserir(Quarto *hotel);
		+ vector<QuartoDTO *> listar();
		+ bool atualizar(int id, const Quarto &quarto);
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoQuarto {
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceApresentacaoReserva {
		+ virtual bool valor()
		+ virtual void setControladoraServicoReserva(InterfaceServicoReserva *controladora_servico_reserva)
	}
}
package "Hotelaria" #LightGreen {
interface InterfaceServicoReserva {
		+ virtual bool valor()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraApresentacaoReserva {
		- InterfaceServicoReserva *controladora_servico_reserva
		+ bool valor() override;
		+ void setControladoraServicoReserva(InterfaceServicoReserva *) override;
	}
}
package "Hotelaria" #LightGreen {
class ControladorInterfaceReserva {
		+ ControladorInterfaceReserva()
	}
}
package "Hotelaria" #LightGreen {
class ControladoraServicoReserva {
	}
}
package "Hotelaria" #LightGreen {
class EnumConversor {
		+ static int StatusSolicitacaoHospedagemParaInteiro(StatusSolicitacaoHospedagem status);
		+ static StatusSolicitacaoHospedagem InteiroParaStatusSolicitacaoHospedagem(int valor);
	}
}
package "Hotelaria" #LightGreen {
enum StatusSolicitacaoHospedagem {
PENDENTE
APROVADO
RECUSADO
	}
}
package "Utils" #DarkBlue {
class Utils {
		- bool verificaSeENumero(const string &str);
	}
}
package "Hotelaria" #LightGreen {
class Versao {
		+ static string getData()
		+ static string getVersaoCompleta()
	}
}
package "IO" #Orange {
class IO {
		- string LerLinha();
		- string LerOpcao();
		- bool tentarNovamente();
		- void Println(const string &mensagem);
		- void Print(const string &mensagem);
	}
}
package "Hotelaria" #LightGreen {
interface ExibirMenu {
	}
}
package "VisualizadorDeMenu" #Gray {
class Menu {
		- vector<MenuItem> menuItens
		- int contador = -1
		+ int adcionarItens(string nome);
		+ vector<MenuItem> listar();
		+ int executa(string tituloStr);
	}
}
package "Hotelaria" #LightGreen {
interface MenuCRUD {
	}
}
package "VisualizadorDeMenu" #Gray {
class MenuItem {
		- string nome
		- string valor
		- int valorConstante
		+ MenuItem(string nomeStr, string valorStr, int valorConstanteInt)
		+ string getNome();
		+ string getValor();
		+ int getValorConstante();
	}
}
package "VisualizadorDeTabela" #Gold {
class Atributo {
		- string nome
		- string valor
		+ Atributo()
		+ Atributo(string nome, string valor)
		+ void setNome(string nome);
		+ void setValor(string valor);
		+ string getNome();
		+ string getValor();
	}
}
package "VisualizadorDeTabela" #Gold {
class Linha {
		- vector<shared_ptr<Atributo> > atributos
		+ Linha()
		+ void atributo(string nome, string valor);
		+ void atributo(string nome, int valor);
		+ vector<shared_ptr<Atributo> > getAtributos();
	}
}
package "VisualizadorDeTabela" #Gold {
class Tabela {
		- vector<shared_ptr<Linha> > linhas
		+ Tabela()
		+ Linha *criarObj();
		+ void exibirTabela(string titulo);
	}
}
package "VisualizadorDeTabela" #Gold {
class TamanhoAtributo {
		- string nome
		- int tamanho = 0
		+ TamanhoAtributo()
		+ TamanhoAtributo(string nome, int tamanho)
		+ void setNome(string nome);
		+ void setTamanho(int tamanho);
		+ string getNome();
		+ int getTamanho();
	}
}
package "Teste" #Purple {
interface InterfaceDeTeste {
		- static int contTodalTestes
		- static int contTodalTestesOk
		- static int contTodalTestesProblema
		- static vector<string> listaFalhas
		+ static const int DEVE_DAR_ERRADO = -1
		+ static const int DEVE_DAR_CERTO = 1
		+ static void checaResultado(int esperando_resultado, int resultado_teste);
		+ static void apresentacaoTeste(const string &valor);
		+ static void apresentacaoTeste(const int &valor);
		+ static void registrarFalha(const string &dominio, const string &entrada, const string &erro);
		+ static int getTestes();
		+ static int getTestesOk();
		+ static int getTestesProblema();
	}
}
package "Teste" #Purple {
class SmokeTeste {
		+ Recebe o valor_teste como string (Implementação no .cpp)
		+ Recebe o valor_teste como Template T (para int, float, etc.)
		+ Recebe o valor_teste como string (Implementação no .cpp)
		+ Recebe o valor_teste como Template T (para int, float, etc.)
	}
}
class TestandoSmoke {
	+ void executarSmokeTest();
	}
class TesteCapacidade {
	+ void executar() override;
	}
class TesteCartao {
	+ void executar() override;
	}
class TesteCodigo {
	+ void executar() override;
	}
class TesteDinheiro {
	+ void executar() override;
	}
class TesteEmail {
	+ void executar() override;
	}
class TesteEndereco {
	+ void executar() override;
	}
class TesteNome {
	+ void executar() override;
	}
class TesteNumero {
	+ void executar() override;
	}
class TesteRamal {
	+ void executar() override;
	}
class TestesData {
	+ void executar() override;
	}
class TesteSenha {
	+ void executar() override;
	}
class TesteTelefone {
	+ void executar() override;
	}
class TesteGerente {
	+ TesteGerente()
	+ void executar() override;
	}
class TesteHospede {
	+ TesteHospede()
	+ void executar() override;
	}
class TesteHotel {
	+ TesteHotel()
	+ void executar() override;
	}
class TesteQuarto {
	+ TesteQuarto()
	+ void executar() override;
	}
class TesteReserva {
	+ TesteReserva()
	+ void executar() override;
	}
Data  --|> exception : Herança
Gerente  --|> Pessoa : Herança
Hospede  --|> Pessoa : Herança
ControladoraApresentacaoAcessoGerente  ..|> InterfaceApresentacaoAcesso : Implementação
ControladoraApresentacaoAcessoHospede  ..|> InterfaceApresentacaoAcesso : Implementação
ControladoraApresentacaoAutenticavel  ..|> InterfaceApresentacaoAutenticavel : Implementação
ControladoraServicoAutenticavel  ..|> InterfaceServicoAutenticavel : Implementação
ControladoraApresentacaoGerente  ..|> InterfaceApresentacaoGerente : Implementação
ControladorInterfaceGerente  --|> ControladoraApresentacaoAutenticavel : Herança
ControladorInterfaceGerente  ..|> MenuCRUD : Implementação
ControladoraServicoGerente  ..|> InterfaceServicoGerente : Implementação
ControladoraApresentacaoHospede  ..|> InterfaceApresentacaoHospede : Implementação
ControladorInterfaceHospede  ..|> MenuCRUD : Implementação
ControladoraServicoHospede  ..|> InterfaceServicoHospede : Implementação
ControladoraApresentacaoHotel  ..|> InterfaceApresentacaoHotel : Implementação
ControladorInterfaceHotel  ..|> ExibirMenu : Implementação
ControladorInterfaceHotel  ..|> MenuCRUD : Implementação
ControladoraServicoHotel  ..|> InterfaceServicoHotel : Implementação
ControladoraApresentacaoQuarto  ..|> InterfaceApresentacaoQuarto : Implementação
ControladorInterfaceQuarto  ..|> ExibirMenu : Implementação
ControladoraServicoQuarto  ..|> InterfaceServicoQuarto : Implementação
ControladoraApresentacaoReserva  ..|> InterfaceApresentacaoReserva : Implementação
ControladorInterfaceReserva  ..|> ExibirMenu : Implementação
ControladoraServicoReserva  ..|> InterfaceServicoReserva : Implementação
TesteCapacidade  ..|> InterfaceDeTeste : Implementação
TesteCartao  ..|> InterfaceDeTeste : Implementação
TesteCodigo  ..|> InterfaceDeTeste : Implementação
TesteDinheiro  ..|> InterfaceDeTeste : Implementação
TesteEmail  ..|> InterfaceDeTeste : Implementação
TesteEndereco  ..|> InterfaceDeTeste : Implementação
TesteNome  ..|> InterfaceDeTeste : Implementação
TesteNumero  ..|> InterfaceDeTeste : Implementação
TesteRamal  ..|> InterfaceDeTeste : Implementação
TestesData  ..|> InterfaceDeTeste : Implementação
TesteSenha  ..|> InterfaceDeTeste : Implementação
TesteTelefone  ..|> InterfaceDeTeste : Implementação
TesteGerente  ..|> InterfaceDeTeste : Implementação
TesteHospede  ..|> InterfaceDeTeste : Implementação
TesteHotel  ..|> InterfaceDeTeste : Implementação
TesteQuarto  ..|> InterfaceDeTeste : Implementação
TesteReserva  ..|> InterfaceDeTeste : Implementação
BancoDeDados  --* Gerente : Composição
BancoDeDados  --* Hospede : Composição
BancoDeDados  --* Hotel : Composição
BancoDeDados  --* Quarto : Composição
BancoDeDados  --* Reserva : Composição
Gerente  --* Email : Composição
Gerente  --* Nome : Composição
Gerente  --* Ramal : Composição
Gerente  --* Senha : Composição
Gerente  --* GerenteDTO : Composição
Hospede  --* Cartao : Composição
Hospede  --* Email : Composição
Hospede  --* Endereco : Composição
Hospede  --* Nome : Composição
Hotel  --* Codigo : Composição
Hotel  --* Endereco : Composição
Hotel  --* Nome : Composição
Hotel  --* Telefone : Composição
Hotel  --* HotelDTO : Composição
Pessoa  --* Email : Composição
Pessoa  --* Nome : Composição
Quarto  --* Capacidade : Composição
Quarto  --* Dinheiro : Composição
Quarto  --* Numero : Composição
Quarto  --* Ramal : Composição
Reserva  --* Codigo : Composição
Reserva  --* Data : Composição
Reserva  --* Dinheiro : Composição
SolicitacaoHospedagem  --* Data : Composição
SolicitacaoHospedagem  --* Hospede : Composição
SolicitacaoHospedagem  --* Hotel : Composição
SolicitacaoHospedagem  --* Quarto : Composição
SolicitacaoHospedagem  --* StatusSolicitacaoHospedagem : Composição
GerenteDTO  --* Email : Composição
GerenteDTO  --* Nome : Composição
GerenteDTO  --* Ramal : Composição
GerenteDTO  --* Gerente : Composição
HospedeDTO  --* Cartao : Composição
HospedeDTO  --* Email : Composição
HospedeDTO  --* Endereco : Composição
HospedeDTO  --* Nome : Composição
HospedeDTO  --* Hospede : Composição
HotelDTO  --* Codigo : Composição
HotelDTO  --* Endereco : Composição
HotelDTO  --* Nome : Composição
HotelDTO  --* Telefone : Composição
HotelDTO  --* Hotel : Composição
PessoaDTO  --* Email : Composição
PessoaDTO  --* Nome : Composição
PessoaDTO  --* Pessoa : Composição
QuartoDTO  --* Capacidade : Composição
QuartoDTO  --* Dinheiro : Composição
QuartoDTO  --* Numero : Composição
QuartoDTO  --* Ramal : Composição
QuartoDTO  --* Quarto : Composição
ReservaDTO  --* Codigo : Composição
ReservaDTO  --* Dinheiro : Composição
ReservaDTO  --* Reserva : Composição
SolicitacaoHospedagemDTO  --* Hospede : Composição
SolicitacaoHospedagemDTO  --* Hotel : Composição
SolicitacaoHospedagemDTO  --* Quarto : Composição
SolicitacaoHospedagemDTO  --* SolicitacaoHospedagem : Composição
Sistema  --* Gerente : Composição
Sistema  --* Hospede : Composição
Sistema  --* ControladoraApresentacaoAcessoGerente : Composição
Sistema  --* ControladoraApresentacaoAcessoHospede : Composição
Sistema  --* Menu : Composição
InterfaceApresentacaoAcesso  --* InterfaceServicoAcesso : Composição
InterfaceApresentacaoAcesso  --* Menu : Composição
ControladoraApresentacaoAcessoGerente  --* Gerente : Composição
ControladoraApresentacaoAcessoGerente  --* InterfaceServicoAcesso : Composição
ControladoraApresentacaoAcessoGerente  --* ControladorInterfaceGerente : Composição
ControladoraApresentacaoAcessoGerente  --* Menu : Composição
ControladoraApresentacaoAcessoHospede  --* InterfaceServicoAcesso : Composição
ControladoraApresentacaoAcessoHospede  --* Menu : Composição
InterfaceApresentacaoAutenticavel  --* Email : Composição
InterfaceApresentacaoAutenticavel  --* InterfaceServicoAutenticavel : Composição
InterfaceApresentacaoAutenticavel  --* ControladoraServicoAutenticavel : Composição
InterfaceServicoAutenticavel  --* Email : Composição
InterfaceServicoAutenticavel  --* Senha : Composição
ControladoraApresentacaoAutenticavel  --* Email : Composição
ControladoraApresentacaoAutenticavel  --* InterfaceServicoAutenticavel : Composição
ControladoraApresentacaoAutenticavel  --* ControladoraServicoAutenticavel : Composição
ControladoraServicoAutenticavel  --* Email : Composição
ControladoraServicoAutenticavel  --* Senha : Composição
InterfaceFabricaGerenciavel  --* FabricaGerenciavel : Composição
InterfaceFabricaGerenciavel  --* Menu : Composição
InterfaceFabricaGerenciavel  --* MenuCRUD : Composição
FabricaGerenciavel  --* Menu : Composição
InterfaceApresentacaoGerente  --* Email : Composição
InterfaceApresentacaoGerente  --* Gerente : Composição
InterfaceApresentacaoGerente  --* Pessoa : Composição
InterfaceApresentacaoGerente  --* InterfaceServicoGerente : Composição
InterfaceServicoGerente  --* Email : Composição
InterfaceServicoGerente  --* Gerente : Composição
ControladoraApresentacaoGerente  --* Email : Composição
ControladoraApresentacaoGerente  --* Gerente : Composição
ControladoraApresentacaoGerente  --* Pessoa : Composição
ControladoraApresentacaoGerente  --* InterfaceServicoGerente : Composição
ControladorInterfaceGerente  --* Gerente : Composição
ControladorInterfaceGerente  --* ControladoraPersistenciaGerente : Composição
ControladorInterfaceGerente  --* Menu : Composição
ControladoraPersistenciaGerente  --* Gerente : Composição
ControladoraPersistenciaGerente  --* GerenteDTO : Composição
ControladoraServicoGerente  --* Email : Composição
ControladoraServicoGerente  --* Gerente : Composição
InterfaceApresentacaoHospede  --* Hospede : Composição
InterfaceApresentacaoHospede  --* InterfaceServicoHospede : Composição
InterfaceApresentacaoHospede  --* ControladoraServicoHospede : Composição
ControladoraApresentacaoHospede  --* Hospede : Composição
ControladoraApresentacaoHospede  --* InterfaceServicoHospede : Composição
ControladoraApresentacaoHospede  --* ControladoraServicoHospede : Composição
ControladorInterfaceHospede  --* Hospede : Composição
ControladorInterfaceHospede  --* ControladoraPersistenciaHospede : Composição
ControladorInterfaceHospede  --* Menu : Composição
ControladoraPersistenciaHospede  --* Hospede : Composição
ControladoraPersistenciaSolicitacaoHospedagem  --* Email : Composição
ControladoraPersistenciaSolicitacaoHospedagem  --* SolicitacaoHospedagem : Composição
InterfaceApresentacaoHotel  --* Hotel : Composição
InterfaceApresentacaoHotel  --* InterfaceServicoHotel : Composição
InterfaceApresentacaoHotel  --* ControladoraServicoHotel : Composição
ControladoraApresentacaoHotel  --* Hotel : Composição
ControladoraApresentacaoHotel  --* InterfaceServicoHotel : Composição
ControladoraApresentacaoHotel  --* ControladoraServicoHotel : Composição
ControladorInterfaceHotel  --* Hotel : Composição
ControladorInterfaceHotel  --* ControladoraPersistenciaHotel : Composição
ControladorInterfaceHotel  --* Menu : Composição
ControladoraPersistenciaHotel  --* Hotel : Composição
ControladoraPersistenciaHotel  --* HotelDTO : Composição
InterfaceApresentacaoQuarto  --* Quarto : Composição
InterfaceApresentacaoQuarto  --* InterfaceServicoQuarto : Composição
InterfaceApresentacaoQuarto  --* ControladoraServicoQuarto : Composição
ControladoraApresentacaoQuarto  --* Quarto : Composição
ControladoraApresentacaoQuarto  --* InterfaceServicoQuarto : Composição
ControladoraApresentacaoQuarto  --* ControladoraServicoQuarto : Composição
ControladorInterfaceQuarto  --* Quarto : Composição
ControladorInterfaceQuarto  --* Menu : Composição
ControladorInterfaceQuarto  --* MenuCRUD : Composição
ControladoraPersistenciaQuarto  --* Quarto : Composição
ControladoraPersistenciaQuarto  --* QuartoDTO : Composição
InterfaceApresentacaoReserva  --* Reserva : Composição
InterfaceApresentacaoReserva  --* InterfaceServicoReserva : Composição
InterfaceApresentacaoReserva  --* ControladoraServicoReserva : Composição
ControladoraApresentacaoReserva  --* Reserva : Composição
ControladoraApresentacaoReserva  --* InterfaceServicoReserva : Composição
ControladoraApresentacaoReserva  --* ControladoraServicoReserva : Composição
ControladoraApresentacaoReserva  --* Menu : Composição
ControladoraApresentacaoReserva  --* MenuCRUD : Composição
ControladorInterfaceReserva  --* Reserva : Composição
ControladorInterfaceReserva  --* Menu : Composição
ControladorInterfaceReserva  --* MenuCRUD : Composição
EnumConversor  --* SolicitacaoHospedagem : Composição
EnumConversor  --* StatusSolicitacaoHospedagem : Composição
Utils  --* Numero : Composição
Versao  --* Data : Composição
IO  --* Linha : Composição
ExibirMenu  --* Menu : Composição
Menu  --* MenuItem : Composição
MenuCRUD  --* Menu : Composição
MenuItem  --* Nome : Composição
MenuItem  --* Menu : Composição
Atributo  --* Nome : Composição
Linha  --* Atributo : Composição
Tabela  --* Linha : Composição
TamanhoAtributo  --* Nome : Composição
TamanhoAtributo  --* Atributo : Composição
TesteGerente  --* Gerente : Composição
TesteHospede  --* Hospede : Composição
TesteHotel  --* Hotel : Composição
TesteQuarto  --* Quarto : Composição
TesteReserva  --* Reserva : Composição
@enduml
