//
// Created by caleb on 01/11/2025.
//

#ifndef GERENCIADOR_DE_HOTEIS_UNB_INTERFACEAPRESENTACAOAUTENTICAVEL_H
#define GERENCIADOR_DE_HOTEIS_UNB_INTERFACEAPRESENTACAOAUTENTICAVEL_H

class IAAutenticavel {
public:
    virtual void fazerLogin() = 0;
};

#endif //GERENCIADOR_DE_HOTEIS_UNB_INTERFACEAPRESENTACAOAUTENTICAVEL_H